import type { CodeTab } from './DpComponents';

export const heroTabs: CodeTab[] = [
  {
    label: 'Node.js',
    lines: [
      [['kw', 'import'], ['', ' '], ['fn', 'WhiteBooks'], ['', ' '], ['kw', 'from'], ['', ' '], ['str', "'@whitebooks/node'"]],
      [['', '']],
      [['kw', 'const'], ['', ' client = '], ['kw', 'new'], ['', ' '], ['fn', 'WhiteBooks'], ['pun', '({']],
      [['', '  apiKey: '], ['key', 'process'], ['pun', '.'], ['fn', 'env'], ['pun', '.'], ['key', 'WB_API_KEY'], ['pun', ',']],
      [['', '  sandbox: '], ['kw', 'false'], ['pun', ',']],
      [['pun', '});']],
      [['', '']],
      [['com', '// Generate an e-invoice (IRN)']],
      [['kw', 'const'], ['', ' irn = '], ['kw', 'await'], ['', ' client'], ['pun', '.'], ['fn', 'einvoice'], ['pun', '.'], ['fn', 'generate'], ['pun', '({']],
      [['', '  gstin: '], ['str', '"29AAGCW7302R1ZF"'], ['pun', ',']],
      [['', '  invoiceType: '], ['str', '"B2B"'], ['pun', ',']],
      [['', '  invoiceNumber: '], ['str', '"INV-001"'], ['pun', ',']],
      [['', '  invoiceDate: '], ['str', '"2024-01-15"'], ['pun', ',']],
      [['pun', '});']],
      [['', '']],
      [['fn', 'console'], ['pun', '.'], ['fn', 'log'], ['pun', '('], ['str', '"IRN:"'], ['', ', irn'], ['pun', '.'], ['key', 'irn'], ['pun', ')']],
    ],
  },
  {
    label: 'Python',
    lines: [
      [['kw', 'import'], ['', ' whitebooks']],
      [['', '']],
      [['fn', 'client'], ['', ' = whitebooks'], ['pun', '.'], ['fn', 'Client'], ['pun', '(']],
      [['', '  api_key='], ['str', '"sk_live_..."'], ['pun', ',']],
      [['', '  sandbox='], ['kw', 'False'], ['pun', ',']],
      [['pun', ')']],
      [['', '']],
      [['com', '# Generate an e-invoice (IRN)']],
      [['fn', 'irn'], ['', ' = client'], ['pun', '.'], ['fn', 'einvoice'], ['pun', '.'], ['fn', 'generate'], ['pun', '(']],
      [['', '  gstin='], ['str', '"29AAGCW7302R1ZF"'], ['pun', ',']],
      [['', '  invoice_type='], ['str', '"B2B"'], ['pun', ',']],
      [['', '  invoice_number='], ['str', '"INV-001"'], ['pun', ',']],
      [['pun', ')']],
      [['', '']],
      [['fn', 'print'], ['pun', '('], ['fn', 'irn'], ['pun', '.'], ['key', 'irn'], ['pun', ')']],
    ],
  },
  {
    label: 'TypeScript',
    lines: [
      [['kw', 'import'], ['', ' '], ['pun', '{'], ['', ' '], ['fn', 'WhiteBooks'], ['', ' '], ['pun', '}'], ['', ' '], ['kw', 'from'], ['', ' '], ['str', "'@whitebooks/node'"], ['pun', ';']],
      [['', '']],
      [['kw', 'const'], ['', ' client = '], ['kw', 'new'], ['', ' '], ['fn', 'WhiteBooks'], ['pun', '({']],
      [['', '  apiKey: '], ['key', 'process'], ['pun', '.'], ['fn', 'env'], ['pun', '.'], ['key', 'WB_API_KEY'], ['pun', '!,']],
      [['', '  sandbox: '], ['kw', 'false'], ['pun', ',']],
      [['pun', '});']],
      [['', '']],
      [['com', '// Generate an e-invoice (IRN)']],
      [['kw', 'const'], ['', ' irn'], ['pun', ':'], ['', ' '], ['fn', 'Einvoice'], ['', ' = '], ['kw', 'await'], ['', ' client'], ['pun', '.'], ['fn', 'einvoice'], ['pun', '.'], ['fn', 'generate'], ['pun', '({']],
      [['', '  gstin: '], ['str', '"29AAGCW7302R1ZF"'], ['pun', ',']],
      [['', '  invoiceType: '], ['str', '"B2B"'], ['pun', ',']],
      [['', '  invoiceNumber: '], ['str', '"INV-001"'], ['pun', ',']],
      [['', '  invoiceDate: '], ['str', '"2024-01-15"'], ['pun', ',']],
      [['pun', '});']],
      [['', '']],
      [['fn', 'console'], ['pun', '.'], ['fn', 'log'], ['pun', '('], ['str', '"IRN:"'], ['', ', irn'], ['pun', '.'], ['key', 'irn'], ['pun', ');']],
    ],
  },
  {
    label: 'Java',
    lines: [
      [['kw', 'import'], ['', ' dev'], ['pun', '.'], ['', 'whitebooks'], ['pun', '.'], ['fn', 'WhiteBooks'], ['pun', ';']],
      [['', '']],
      [['fn', 'WhiteBooks'], ['', ' client = '], ['fn', 'WhiteBooks'], ['pun', '.'], ['fn', 'builder'], ['pun', '()']],
      [['', '    '], ['pun', '.'], ['fn', 'apiKey'], ['pun', '('], ['fn', 'System'], ['pun', '.'], ['fn', 'getenv'], ['pun', '('], ['str', '"WB_API_KEY"'], ['pun', '))']],
      [['', '    '], ['pun', '.'], ['fn', 'sandbox'], ['pun', '('], ['kw', 'false'], ['pun', ')']],
      [['', '    '], ['pun', '.'], ['fn', 'build'], ['pun', '();']],
      [['', '']],
      [['com', '// Generate an e-invoice (IRN)']],
      [['fn', 'Einvoice'], ['', ' irn = client'], ['pun', '.'], ['fn', 'einvoice'], ['pun', '()'], ['pun', '.'], ['fn', 'generate'], ['pun', '(']],
      [['', '    '], ['fn', 'EinvoiceParams'], ['pun', '.'], ['fn', 'builder'], ['pun', '()']],
      [['', '        '], ['pun', '.'], ['fn', 'gstin'], ['pun', '('], ['str', '"29AAGCW7302R1ZF"'], ['pun', ')']],
      [['', '        '], ['pun', '.'], ['fn', 'invoiceType'], ['pun', '('], ['str', '"B2B"'], ['pun', ')']],
      [['', '        '], ['pun', '.'], ['fn', 'invoiceNumber'], ['pun', '('], ['str', '"INV-001"'], ['pun', ')']],
      [['', '        '], ['pun', '.'], ['fn', 'invoiceDate'], ['pun', '('], ['str', '"2024-01-15"'], ['pun', ')']],
      [['', '        '], ['pun', '.'], ['fn', 'build'], ['pun', '());']],
      [['', '']],
      [['fn', 'System'], ['pun', '.'], ['key', 'out'], ['pun', '.'], ['fn', 'println'], ['pun', '('], ['str', '"IRN: "'], ['', ' + irn'], ['pun', '.'], ['fn', 'getIrn'], ['pun', '());']],
    ],
  },
  {
    label: 'Go',
    lines: [
      [['kw', 'import'], ['', ' '], ['str', '"github.com/whitebooks/whitebooks-go"']],
      [['', '']],
      [['', 'client := whitebooks'], ['pun', '.'], ['fn', 'NewClient'], ['pun', '(']],
      [['', '    os'], ['pun', '.'], ['fn', 'Getenv'], ['pun', '('], ['str', '"WB_API_KEY"'], ['pun', '),']],
      [['', '    whitebooks'], ['pun', '.'], ['fn', 'WithSandbox'], ['pun', '('], ['kw', 'false'], ['pun', '),']],
      [['pun', ')']],
      [['', '']],
      [['com', '// Generate an e-invoice (IRN)']],
      [['', 'irn, err := client'], ['pun', '.'], ['key', 'Einvoice'], ['pun', '.'], ['fn', 'Generate'], ['pun', '(ctx, &whitebooks'], ['pun', '.'], ['fn', 'EinvoiceParams'], ['pun', '{']],
      [['', '    '], ['key', 'GSTIN'], ['pun', ':'], ['', '         '], ['str', '"29AAGCW7302R1ZF"'], ['pun', ',']],
      [['', '    '], ['key', 'InvoiceType'], ['pun', ':'], ['', '   '], ['str', '"B2B"'], ['pun', ',']],
      [['', '    '], ['key', 'InvoiceNumber'], ['pun', ':'], ['', ' '], ['str', '"INV-001"'], ['pun', ',']],
      [['', '    '], ['key', 'InvoiceDate'], ['pun', ':'], ['', '   '], ['str', '"2024-01-15"'], ['pun', ',']],
      [['pun', '})']],
      [['', '']],
      [['fn', 'fmt'], ['pun', '.'], ['fn', 'Println'], ['pun', '('], ['str', '"IRN:"'], ['', ', irn'], ['pun', '.'], ['key', 'IRN'], ['pun', ')']],
    ],
  },
  {
    label: 'PHP',
    lines: [
      [['kw', 'use'], ['', ' '], ['fn', 'WhiteBooks'], ['pun', '\\'], ['fn', 'Client'], ['pun', ';']],
      [['', '']],
      [['key', '$client'], ['', ' = '], ['kw', 'new'], ['', ' '], ['fn', 'Client'], ['pun', '([']],
      [['', '    '], ['str', "'api_key'"], ['', ' => '], ['fn', 'getenv'], ['pun', '('], ['str', "'WB_API_KEY'"], ['pun', '),']],
      [['', '    '], ['str', "'sandbox'"], ['', ' => '], ['kw', 'false'], ['pun', ',']],
      [['pun', ']);']],
      [['', '']],
      [['com', '// Generate an e-invoice (IRN)']],
      [['key', '$irn'], ['', ' = '], ['key', '$client'], ['pun', '->'], ['fn', 'einvoice'], ['pun', '->'], ['fn', 'generate'], ['pun', '([']],
      [['', '    '], ['str', "'gstin'"], ['', ' => '], ['str', '"29AAGCW7302R1ZF"'], ['pun', ',']],
      [['', '    '], ['str', "'invoice_type'"], ['', ' => '], ['str', '"B2B"'], ['pun', ',']],
      [['', '    '], ['str', "'invoice_number'"], ['', ' => '], ['str', '"INV-001"'], ['pun', ',']],
      [['', '    '], ['str', "'invoice_date'"], ['', ' => '], ['str', '"2024-01-15"'], ['pun', ',']],
      [['pun', ']);']],
      [['', '']],
      [['kw', 'echo'], ['', ' '], ['key', '$irn'], ['pun', '->'], ['key', 'irn'], ['pun', ';']],
    ],
  },
  {
    label: 'cURL',
    lines: [
      [['fn', 'curl'], ['', ' -X POST \\']],
      [['str', '  "https://api.whitebooks.dev/v3/einvoice/generate"'], ['', ' \\']],
      [['', '  -H '], ['str', '"Authorization: Bearer sk_live_..."'], ['', ' \\']],
      [['', '  -H '], ['str', '"Content-Type: application/json"'], ['', ' \\']],
      [['', '  -d '], ['str', '\'{"gstin":"29AAGCW7302R1ZF",']],
      [['str', '    "invoiceType":"B2B",']],
      [['str', '    "invoiceNumber":"INV-001",']],
      [['str', '    "invoiceDate":"2024-01-15"}\'']],
    ],
  },
];

export const quickstartReqTabs: CodeTab[] = [
  {
    label: 'Request',
    lines: [
      [['com', '// 1. Install the SDK']],
      [['fn', 'npm'], ['', ' install @whitebooks/node']],
      [['', '']],
      [['com', '// 2. Initialize']],
      [['kw', 'const'], ['', ' wb = '], ['kw', 'new'], ['', ' '], ['fn', 'WhiteBooks'], ['pun', '({'], ['', ' apiKey '], ['pun', '})']],
      [['', '']],
      [['com', '// 3. Generate IRN']],
      [['kw', 'const'], ['', ' result = '], ['kw', 'await'], ['', ' wb'], ['pun', '.'], ['fn', 'einvoice'], ['pun', '.'], ['fn', 'generate'], ['pun', '(payload)']],
    ],
  },
];

export const quickstartRespTabs: CodeTab[] = [
  {
    label: 'Response',
    lines: [
      [['pun', '{']],
      [['', '  '], ['key', '"irn"'], ['pun', ':'], ['', ' '], ['str', '"e9fc7b4b2c1a..."'], ['pun', ',']],
      [['', '  '], ['key', '"ackNo"'], ['pun', ':'], ['', ' '], ['num', '232410297398'], ['pun', ',']],
      [['', '  '], ['key', '"ackDt"'], ['pun', ':'], ['', ' '], ['str', '"2024-01-15T10:30:00"'], ['pun', ',']],
      [['', '  '], ['key', '"signedQRCode"'], ['pun', ':'], ['', ' '], ['str', '"MSME/2024/..."'], ['pun', ',']],
      [['', '  '], ['key', '"status"'], ['pun', ':'], ['', ' '], ['str', '"success"']],
      [['pun', '}']],
    ],
  },
];
